<?php

/**
 * @file
 * This is a basic block module that provides an Ajax dependent dropdown form
 * Author:  joshisa@us.ibm.com
 */


/*
 * Implementation of hook_form_alter()
 */
function restaurant_reservation_multistep_form_eck__entity__form_add_reservation_reservation_alter(&$form, &$form_state, $form_id){
  dsm($form);
  dsm($form_id);
  drupal_set_message('<pre>' . print_r($form, true) . '</pre>');
  // Add the check box
  $form['certify'] = array(
    '#type' => 'checkbox',
    '#title' => t('I certify that this is really awesome'),
  );
  //$form['field_reservation_cake_type']['und'][0]]
}
