<?php

/**
 * @file
 * This is a basic block module that provides an Ajax dependent dropdown form
 * Author:  joshisa@us.ibm.com
 */


/*
 * Implementation of hook_form_alter()
 */
function restaurant_reservation_multistep_form_alter(&$form, &$form_state, $form_id){
  dsm($form);
  dsm($form_id);
  // Check when the right form is passed
  if ($form_id == 'eck__entity__form_add_reservation_reservation') {
    // Add the check box
    $form['certify'] = array(
      '#type' => 'checkbox',
      '#title' => t('I certify that this is my true name'),
    );
  }
}
