<?php

/**
 * @file
 * This is a basic block module that provides an Ajax dependent dropdown form
 * Author:  joshisa@us.ibm.com
 */

/**
 * Implements hook_block_info().
 */
function restaurant_reservation_multistep_block_info() {
  $blocks = array();
  $blocks['restaurant_reservation_multistep'] = array(
    'info' => t('MultiStep Form'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view.
 */
function restaurant_reservation_multistep_block_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'restaurant_reservation_multistep':
        $block['subject'] = '';
        $block['content'] = _restaurant_reservation_multistep_block_block_content();
        break;
    default:
        $block['subject'] = '';
        $block['content'] = t('Default');
  }
  return $block;
}

function _restaurant_reservation_multistep_block_block_content() {
  $output = t('Hello World!');
  return $output;
}
